import { ColorPalette } from "@/types/logo";

export const PREDEFINED_COLORS = [
  { name: "العنابي الملكي", hex: "#531B23" },
  { name: "الذهب الملكي", hex: "#C9A227" },
  { name: "الذهب الفاتح", hex: "#D4AF37" },
  { name: "الأخضر الزمردي", hex: "#1B5E20" },
  { name: "الأخضر الماسي", hex: "#2E7D32" },
  { name: "الأزرق الكحلي", hex: "#0D1B2A" },
  { name: "أزرق ياقوتي", hex: "#1B4965" },
  { name: "الأزرق السماوي", hex: "#0288D1" },
  { name: "البنفسجي الإمبراطوري", hex: "#4A154B" },
  { name: "الأرجواني الملكي", hex: "#6A1B9A" },
  { name: "النبيذي الفاخر", hex: "#8B1E2E" },
  { name: "الأحمر الياقوتي", hex: "#B71C1C" },
  { name: "الفحمي الحالك", hex: "#1A1A1A" },
  { name: "الرمادي الصخري", hex: "#374151" },
  { name: "الرمادي الفضي", hex: "#9CA3AF" },
  { name: "الفضي البلاتيني", hex: "#E5E7EB" },
  { name: "الأبيض النقي", hex: "#FFFFFF" },
  { name: "العاجي الدافئ", hex: "#FDFBF7" },
];

export const PREDEFINED_PALETTES: ColorPalette[] = [
  {
    id: "original_heritage",
    name: "الهوية الملكية الكلاسيكية",
    description: "الألوان الرسمية المتوارثة للجامعة اليمنية الإلكترونية",
    colors: {
      symbol_y: "#531B23",
      symbol_e: "#531B23",
      symbol_u: "#531B23",
      symbol_squares: "#C9A227",
      text_arabic: "#531B23",
      text_english: "#531B23",
    },
    background: { type: "transparent" },
  },
  {
    id: "royal_gold_prestige",
    name: "الفخامة الملكية والذهب",
    description: "تناغم ملكي بين العنابي الداكن والذهب الخالص",
    colors: {
      symbol_y: "#531B23",
      symbol_e: "#70393D",
      symbol_u: "#70393D",
      symbol_squares: "#D4AF37",
      text_arabic: "#531B23",
      text_english: "#8C6219",
    },
    background: { type: "solid", color: "#FDFBF7" },
  },
  {
    id: "digital_innovation",
    name: "الابتكار الرقمي",
    description: "حداثة التعليم الإلكتروني والذكاء المستقبلي",
    colors: {
      symbol_y: "#0077B6",
      symbol_e: "#023E8A",
      symbol_u: "#023E8A",
      symbol_squares: "#48CAE4",
      text_arabic: "#03045E",
      text_english: "#0077B6",
    },
    background: { type: "transparent" },
  },
  {
    id: "green_vision",
    name: "الرؤية والازدهار",
    description: "مستوحى من النهضة والازدهار ونماء التعليم المستدام",
    colors: {
      symbol_y: "#1B5E20",
      symbol_e: "#2E7D32",
      symbol_u: "#2E7D32",
      symbol_squares: "#C9A227",
      text_arabic: "#1B5E20",
      text_english: "#2E7D32",
    },
    background: { type: "transparent" },
  },
  {
    id: "academic_navy",
    name: "الهيبة الأكاديمية",
    description: "الأزرق الكحلي مع لمسات فضية وبلاتينية رصينة",
    colors: {
      symbol_y: "#0D1B2A",
      symbol_e: "#1B263B",
      symbol_u: "#1B263B",
      symbol_squares: "#415A77",
      text_arabic: "#0D1B2A",
      text_english: "#415A77",
    },
    background: { type: "solid", color: "#FFFFFF" },
  },
  {
    id: "dark_elegance",
    name: "الوضع الليلي الفاخر",
    description: "شعار ذهبي متباين على خلفية داكنة فخمة",
    colors: {
      symbol_y: "#D4AF37",
      symbol_e: "#E0BD53",
      symbol_u: "#E0BD53",
      symbol_squares: "#FFFFFF",
      text_arabic: "#FFFFFF",
      text_english: "#D4AF37",
    },
    background: { type: "solid", color: "#121212" },
  },
  {
    id: "creative_purple",
    name: "الإبداع والتميز",
    description: "تدرجات البنفسجي الملكي مع لمسات ذهبية مشرقة",
    colors: {
      symbol_y: "#4A154B",
      symbol_e: "#6A1B9A",
      symbol_u: "#6A1B9A",
      symbol_squares: "#E0A922",
      text_arabic: "#4A154B",
      text_english: "#6A1B9A",
    },
    background: { type: "transparent" },
  },
  {
    id: "modern_monochrome",
    name: "الأحادي العصري",
    description: "طابع نقي وحاد بالأبيض والأسود والرمادي المصقول",
    colors: {
      symbol_y: "#18181B",
      symbol_e: "#27272A",
      symbol_u: "#27272A",
      symbol_squares: "#71717A",
      text_arabic: "#18181B",
      text_english: "#52525B",
    },
    background: { type: "transparent" },
  },
];
